# Generated by Django 4.2.1 on 2023-05-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (id, title)
            VALUES (1, 'collection1')
        """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
