# Generated by Django 4.2.2 on 2023-06-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cartitem_cart_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
